### ISSUE TITLE
FullPromise中用到原生Promise

### ISSUE THREAD

**Issue by RichardWSD** [su37josephxia/wheel-awesome#48]
在FullPromise中用到了原生Promise，这应该不算手写实现promise用法吧？

**Comment by su37josephxia** [comment]
https://github.com/su37josephxia/wheel-awesome/tree/master/promise
可以看看他的说明 是继承关系 目前提交的原则是只要测试通过并且没有过多cp别人的代码就可以
倡导从零到一 可以考虑PR修正一他的代码
