### ISSUE TITLE
排序（冒泡、快排、选择）这部分

### ISSUE THREAD

**Issue by su37josephxia** [su37josephxia/wheel-awesome#72]
排序（冒泡、快排、选择） 有没有兄弟搞一下 
目前已经有一个冒泡 排序了  后面两种以及其他排序 
还有关于排序效率 和复杂度的比对 大家都可以做

**Comment by 224137748** [comment]
## 冒泡排序

**冒泡排序**：比较所有相邻的两个项，如果第一个比第二个大，则交换他们。元素项向上移动至正确的顺序，就好像气泡升至表面一样，冒泡排序 因此得名。

### 动画原理

![这是图片](https://www.runoob.com/wp-content/uploads/2019/03/bubbleSort.gif "冒泡排序动画展示")

### 代码实现

```javascript
// 常量
const Compare = {
  BIGGER_THAN: "BIGGER_THAN",
  LESS_THAN: "LESS_THAN",
};

// 比较函数
const compareFn = (a, b) => {
  return a < b ? Compare.LESS_THAN : Compare.BIGGER_THAN;
};

// 冒泡排序
function bubbleSort(array) {
  const length = array.length;                                          // {1}
  for (let i = 0; i < length; i++) {                                    // {2}
    for (let j = 0; j < length - 1 - i; j++) {                          // {3}
      if (compareFn(array[j], array[j + 1]) === Compare.BIGGER_THAN) {  // {4}
        // 调换位置
        [array[j], array[j + 1]] = [array[j + 1], array[j]];            // {5}
      }
    }
  }
  return array;
}
```

### 代码分析

- 由上图可知，外循环 `(行{2})` 会从数组的第一位迭代至最后一位，它控制了在数组中经过多少轮排序，外圈循环一次就会找到一个最大值，或最小值。
- 内循环 `(行{3})` 将从第一位迭代至倒数第`length - 1- i`位，内循环实际上进行当前项和下一项的比较 `(行{4})`。
- 如果两项顺序不对（当前项比下一项大），则交换它们 `(行{5})`，意思是位置为 `j+1` 的值将会被置换到位置 `j` 处，反之亦然。

### 复杂度

- 空间复杂度： 冒泡排序函数并没有增加多余的存储变量，所以复杂度为`O(1)`
- 时间复杂度：两次 `for` 循环遍历数组，数组长度为 `n`，则复杂度为 `O(n2)`

**Comment by su37josephxia** [comment]
不错可以 提一个代码出来

**Comment by YouYouzmr** [comment]
### 快排算法
是一个分块交换排序，在平均状况下，排序n个项目需要O(nlogn)次比较。最坏情况O(n^2) 次比较
### 原理
* 选一个基准值
* 排序数组，小于基准值放左边，大于放右边
* 最后递归，重复上述2步即可
![image](https://user-images.githubusercontent.com/22805106/130380989-5cfccdd3-9fb8-4ac2-84fe-58772e5b5a41.png)

### 代码实现
``` js
function quick_sort(arr, l, r) {
    if(l >= r) return;
    let x = l, y = r, base = arr[l];
    while(x < y) {
        while(x < y && arr[y] >= base) y--;
        if(x < y) arr[x++] = arr[y];
        while(x < y && arr[x] < base) x++;
        if(x < y) arr[y--] = arr[x];
    }
    
    arr[x] = base;
    quick_sort(arr, l, x - 1);
    quick_sort(arr, x + 1, r);
    return;
}
```
